name = "diet"
compatibility_date = "2025-06-13"      # 请根据需要使用最新日期
workers_dev = true                     # 使用 *.workers.dev 默认子域名
main = "./index.ts"  # 指向构建后的 API 入口文件

[build]
command = "pnpm run build"  # 使用 pnpm 运行构建命令

[assets]
directory = "./packages/client/dist"   # 指向前端构建输出目录
binding = "ASSETS"                     # 资源绑定名称
not_found_handling = "single-page-application"  # SPA 路由模式

[ai]
binding = "AI"

[observability.logs]
enabled = true

# 环境变量配置示例 - 实际值请通过 Cloudflare 控制台或 wrangler secret 设置
[vars]
# 百度 AI 配置
BAIDU_API_KEY = "your-baidu-api-key"
BAIDU_SECRET_KEY = "your-baidu-secret-key"
BAIDU_MODEL = "ERNIE-Bot-4"

# 通义千问配置
DASHSCOPE_API_KEY = "your-dashscope-api-key"
QWEN_MODEL = "qwen-max"
# Cloudflare 配置
CLOUDFLARE_WORKERS_AI_API_TOKEN = "OiAqDggSK8CZ3T_8KR1KaAYIUne0EbTmeazkHZY9"
CLOUDFLARE_ACCOUNT_ID = "d0b62cca82046c4762524de0c436d366"
CLOUDFLARE_MODEL = "@cf/deepseek-ai/deepseek-r1-distill-qwen-32b"
